name: Workflow Test POC

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

permissions:
 id-token: write # required to use OIDC authentication
 contents: read # required to checkout the code from the repo

jobs:
  test:
    name: Test workflow
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_ARN }}
          role-session-name: ${{ vars.RESOURCE_PREFIX }}bot-build
          aws-region: ${{ vars.AWS_REGION }}